apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: monitoring
  labels:
    name: longhorn-prometheus-servicemonitor
    app: longhorn-manager
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - longhorn-system
  selector:
    matchLabels:
      app: longhorn-manager
  endpoints:
  - port: manager