apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ${name}
spec:
  provider:
    aws:
      service: ${service}
      region: ${region}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: eso-aws-creds
            namespace: ${eso_namespace}
            key: access-key
          secretAccessKeySecretRef:
            name: eso-aws-creds
            namespace: ${eso_namespace}
            key: secret-access-key