redis-ha:
  enabled: true
  replicas: 2

controller:
  replicas: 1

repoServer:
  replicas: 2

applicationSet:
  enabled: true
  replicas: 2

global:
  domain: argocd.home.beabys.com

configs:
  url: https://argocd.home.beabys.com
  params:
    server.insecure: true

server:
  replicas: 2
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.tls: "false"
    hosts:
      -  argocd.home.beabys.com