apiVersion: fission.io/v1
kind: Function
metadata:
  name: hello-world
  namespace: ${fission_namespace}
spec:
  environment:
    name: python-warm
    namespace: ${fission_namespace}
  InvokeStrategy:
    StrategyType: execution
    ExecutionStrategy:
      ExecutorType: poolmgr
      MinScale: 1
      MaxScale: 1
  package:
    functionName: main
    packageref:
      name: hello-world-pkg
      namespace: ${fission_namespace}