apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-server
  namespace: grafana-loki
spec:
  ingressClassName: traefik
  rules:
  - host: loki.home.beabys.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki
            port:
              number: 3100
