csi:
  kubeletRootDir: "/var/lib/kubelet"

defaultSettings:
  diskType: "filesystem"
  concurrentReplicaRebuildPerNodeLimit: 1

longhornManager:
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 256Mi

longhornUI:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi