---
# Docker host
# docker_host_ip is defined in host_vars/docker-host.yml

# HAProxy
haproxy_image: haproxy:latest
haproxy_container_name: k3s-haproxy
haproxy_port: 6443
haproxy_memory_limit: 2g
haproxy_config_dir: /usr/local/etc/haproxy

# MariaDB
mariadb_image: mariadb:latest
mariadb_container_name: k3s-db
mariadb_port: 3306
mariadb_database: k3sdb
mariadb_user: k3s
mariadb_password: k3spass
mariadb_root_password: k3spass
mariadb_memory_limit: 2g
mariadb_memory_reservation: 1g
mariadb_buffer_pool_size: 1434M
mariadb_data_dir: /var/lib/mysql

# K3s
k3s_version: ""
k3s_datastore_endpoint: "mysql://k3s:k3spass@tcp({{ hostvars['docker-host']['docker_host_ip'] }}:3306)/k3sdb"
k3s_tls_san: "{{ hostvars['docker-host']['docker_host_ip'] }}"
k3s_disable:
  - traefik
  - servicelb
  - local-storage
k3s_flannel_backend: host-gw
k3s_token_file: /tmp/.k3s-token
k3s_server_url: "https://{{ hostvars['docker-host']['docker_host_ip'] }}:6443"
k3s_dns_upstream: 10.27.10.1
