ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
    matchRule: Host(`traefik.home.beabys.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    middlewares:
      - name: traefik-dashboard-auth
