---
traefik_namespace: traefik
traefik_chart: traefik/traefik
traefik_repo_url: https://traefik.github.io/charts
traefik_release_name: traefik
traefik_dashboard_user: admin
traefik_dashboard_password: admin
traefik_dashboard_domain: "traefik.home.lab"
