[docker_host]
docker-host ansible_host=10.27.10.50

[masters]
k3s-m1 ansible_host=10.27.10.51
k3s-m2 ansible_host=10.27.10.52

[workers]
k3s-w1 ansible_host=10.27.10.53
k3s-w2 ansible_host=10.27.10.54
